In [1]:
import sys, os

In [2]:
sys.path.append(os.pardir)
from dataset.mnist import load_mnist

In [ ]:
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)

In [ ]:
print(x_train.shape)
print(t_train.shape)
print(x_test.shape)
print(t_test.shape)

In [3]:
import numpy as np

In [ ]:
from PIL import Image

In [ ]:
def img_show(img):
    pil_img = Image.fromarray(np.uint8(img))
    pil_img.show()
    
img = x_train[0]
label = t_train[0]
print(label)

print(img.shape)
img = img.reshape(28, 28)
print(img.shape)

In [ ]:
img_show(img)

In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [5]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [6]:
def get_data():
    (x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, flatten=True, one_hot_label=False)
    return x_test, t_test

In [7]:
def init_network():
    with open('sample_weight.pkl', 'rb') as f:
        network = pickle.load(f)
    return network

In [8]:
def predict(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = softmax(a3)
    
    return y

In [9]:
import pickle

In [10]:
x, t = get_data()
network = init_network()

In [ ]:
accuracy_cnt = 0
for i in range(len(x)):
    y = predict(network, x[i])
    p = np.argmax(y)
    if p == t[i]:
        accuracy_cnt += 1
        
print('accuracy: ' + str(accuracy_cnt / len(x)))

In [16]:
W1, W2, W3 = network['W1'], network['W2'], network['W3']
print(x.shape)
print(x[0].shape)
print(W1.shape)
print(W2.shape)
print(W3.shape)

(10000, 784)
(784,)
(784, 50)
(50, 100)
(100, 10)


### 배치 처리

In [21]:
batch_size = 100
accuracy_cnt = 0

for i in range(0, len(x), batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = predict(network, x_batch)
    p = np.argmax(y_batch, axis=1)
    accuracy_cnt += np.sum(p == t[i:i+batch_size])

print('accuracy: ' + str(accuracy_cnt / len(x)))

accuracy: 0.9352


In [23]:
list(range(0, 1000, 100))

[0, 100, 200, 300, 400, 500, 600, 700, 800, 900]

In [25]:
arr = np.array([[0.1, 0.8, 0.1], [0.3, 0.1, 0.6], [0.2, 0.5, 0.3], [0.8, 0.1, 0.1]])
arr

array([[0.1, 0.8, 0.1],
       [0.3, 0.1, 0.6],
       [0.2, 0.5, 0.3],
       [0.8, 0.1, 0.1]])

In [27]:
# axis=1 : 열의 나열 방향으로(=각 행별로) 최대값 찾아서 인덱스를 배열로 반환
print(np.argmax(arr, axis=1))

[1 2 1 0]


In [28]:
# axis=0 : 행의 나열 방향으로(=각 열별로) 최대값 찾아서 인덱스를 배열로 반환
print(np.argmax(arr, axis=0))

[3 0 1]
